# Generated by Django 5.1.6 on 2026-03-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
