# Generated by Django 6.0.6 on 2026-06-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("ADMIN_LOGIN", "Admin Login"),
                    ("LOGIN_OTP_SENT", "Login Otp Sent"),
                    ("LOGIN_OTP_RESENT", "Login Otp Resent"),
                    ("OTP_SENT", "Otp Sent"),
                    ("OTP_FAILED", "Otp Failed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("PASSWORD_RESET_OTP_SENT", "Password Reset Otp Sent"),
                    ("PASSWORD_RESET_SUCCESS", "Password Reset Success"),
                    ("REGISTER_VENDOR", "Register Vendor"),
                    ("REGISTER_ORGANIZATION", "Register Organization"),
                    ("CATEGORY_CREATED", "Category Created"),
                    ("CATEGORY_UPDATED", "Category Updated"),
                    ("CATEGORY_STATUS_UPDATED", "Category Status Updated"),
                    ("VENDOR_APPROVED", "Vendor Approved"),
                    ("VENDOR_REJECTED", "Vendor Rejected"),
                    ("VENDOR_STATUS_UPDATED", "Vendor Status Updated"),
                    ("RFP_CREATED", "Rfp Created"),
                    ("RFP_UPDATED", "Rfp Updated"),
                    ("RFP_STATUS_UPDATED", "Rfp Status Updated"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rfp",
            name="assigned_vendors",
            field=models.ManyToManyField(
                blank=True, related_name="rfps", to="rfp.vendor"
            ),
        ),
    ]
