# Generated by Django 5.1.6 on 2026-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0003_remove_authconfig_otp_expiry_minutes_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="otp_expiry_minutes",
        ),
        migrations.AddField(
            model_name="authconfig",
            name="otp_expiry_minutes",
            field=models.IntegerField(default=10),
        ),
    ]
