# Generated by Django 5.1.6 on 2026-05-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0004_remove_activitylog_otp_expiry_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginotp",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="max_attempts",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="otp_type",
            field=models.CharField(
                choices=[("LOGIN", "Login"), ("PASSWORD_RESET", "Password Reset")],
                default="LOGIN",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loginotp",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loginotp",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="loginotp",
            name="otp",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="loginotp",
            index=models.Index(fields=["email"], name="rfp_loginot_email_64ae35_idx"),
        ),
        migrations.AddIndex(
            model_name="loginotp",
            index=models.Index(
                fields=["expires_at"], name="rfp_loginot_expires_09da9f_idx"
            ),
        ),
    ]
