# Generated by Django 5.1.6 on 2026-05-10 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0005_loginotp_attempts_loginotp_ip_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="activitylog",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="request_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="role",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("CRITICAL", "Critical"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("OTP_SENT", "Otp Sent"),
                    ("OTP_FAILED", "Otp Failed"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("CATEGORY_CREATED", "Category Created"),
                    ("CATEGORY_UPDATED", "Category Updated"),
                    ("VENDOR_APPROVED", "Vendor Approved"),
                    ("VENDOR_REJECTED", "Vendor Rejected"),
                    ("RFP_CREATED", "Rfp Created"),
                    ("RFP_UPDATED", "Rfp Updated"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["timestamp"], name="rfp_activit_timesta_4b1821_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["action"], name="rfp_activit_action_70fc19_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["model_name"], name="rfp_activit_model_n_65f400_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["user"], name="rfp_activit_user_id_8ee31a_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["ip_address"], name="rfp_activit_ip_addr_04265b_idx"
            ),
        ),
    ]
