# Generated by Django 5.1.6 on 2026-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0006_alter_activitylog_options_activitylog_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="google_auth_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vendor",
            name="google_auth_secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
